// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","id":"1"},"2":{"path":"/drilldown","id":"2"},"3":{"path":"/slo","id":"3"},"4":{"path":"/roi","id":"4"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__CostOverviewPage" */'@/pages/CostOverviewPage.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__DrilldownPage" */'@/pages/DrilldownPage.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__SLODashboard" */'@/pages/SLODashboard.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__ROIDashboard" */'@/pages/ROIDashboard.tsx')),
},
  };
}
